name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test against'
        required: false
        default: 'dev'
        type: choice
        options:
        - dev
        - staging
      project:
        description: 'Browser/Project to test with'
        required: false
        default: 'Chromium'
        type: choice
        options:
        - Chromium
        - Firefox
        - WebKit

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: npx playwright test --project=${{ github.event.inputs.project || 'Chromium' }}
      env:
        TEST_ENV: ${{ github.event.inputs.environment || 'dev' }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ github.event.inputs.environment || 'dev' }}-${{ github.event.inputs.project || 'Chromium' }}
        path: |
          playwright-report/
          test-results/
        retention-days: 30
    
    - name: Generate Allure Report
      if: always()
      run: |
        npx allure generate ./allure-results -o ./allure-report
    
    - name: Serve Allure Report (for debugging)
      if: always()
      run: |
        echo "To view the Allure report, run: npx allure open ./allure-report"
        echo "Or serve it locally: npx allure serve ./allure-results"
    
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report-${{ github.event.inputs.environment || 'dev' }}-${{ github.event.inputs.project || 'Chromium' }}
        path: allure-report/
        retention-days: 30 