name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test against'
        required: false
        default: 'dev'
        type: choice
        options:
        - dev
        - staging

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: npx playwright test
      env:
        TEST_ENV: ${{ github.event.inputs.environment || 'dev' }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ github.event.inputs.environment || 'dev' }}
        path: |
          playwright-report/
          test-results/
        retention-days: 30
    
    - name: Generate Allure Report
      if: always()
      run: |
        npx allure generate ./allure-results --clean -o ./allure-report
    
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report-${{ github.event.inputs.environment || 'dev' }}
        path: allure-report/
        retention-days: 30

  test-staging:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: test
    if: github.event.inputs.environment == 'staging' || github.event.inputs.environment == null
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests on staging
      run: npx playwright test
      env:
        TEST_ENV: staging
    
    - name: Upload staging test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-staging
        path: |
          playwright-report/
          test-results/
        retention-days: 30 